use anchor_lang::prelude::*;

declare_program!(raydium_cp_swap);

pub use crate::raydium_cp_swap::*;

// Re-export states module - account types are generated by declare_program!
pub mod states {
    // Re-export account types from the generated program module
    // The declare_program! macro generates these in the accounts submodule
    pub use crate::raydium_cp_swap::accounts::{AmmConfig, ObservationState, PoolState};

    // Seed constants
    pub const OBSERVATION_SEED: &str = "observation";
    pub const POOL_SEED: &str = "pool";
    pub const POOL_LP_MINT_SEED: &str = "pool_lp_mint";
    pub const POOL_VAULT_SEED: &str = "pool_vault";
}

// Seed constants at root level
pub const AUTH_SEED: &str = "vault_and_lp_mint_auth_seed";

// Create pool fee receiver PDA
pub mod create_pool_fee_reveiver {
    use anchor_lang::prelude::Pubkey;

    pub fn id() -> Pubkey {
        // Mainnet create pool fee receiver
        Pubkey::try_from("DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8").unwrap()
    }
}
